kind: ConfigMap
apiVersion: v1
metadata:
  name: fluentd-config
  namespace: {{ .Values.fluentd.namespace }}
data:
  kubernetes.conf: |-
    {{- include "kubernetes.conf" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluentd
  namespace: {{ .Values.fluentd.namespace }}
  labels:
    app: fluentd

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd
roleRef:
  kind: ClusterRole
  name: fluentd
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: {{ .Values.fluentd.namespace }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: {{ .Values.fluentd.namespace }}
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.15.3-debian-elasticsearch7-1.0
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "elasticsearch.{{ .Values.fluentd.namespace }}.svc.cluster.local"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
          resources:
            limits:
              cpu: {{ .Values.fluentd.resources.limits.cpu }}
              memory: {{ .Values.fluentd.resources.limits.memory }}
            requests:
              cpu: {{ .Values.fluentd.resources.requests.cpu }}
              memory: {{ .Values.fluentd.resources.requests.memory }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluentd/etc/kubernetes.conf
              subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: fluentd-config