{{- $appName := (include "higress-console-fluentd.fullname" .) }}
{{- $esName := (include "higress-console-es.fullname" .) }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
data:
  kubernetes.conf: |-
    {{- include "kubernetes.conf" . | nindent 4 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $appName }}
  labels:
    app: {{ $appName }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $appName }}

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $appName }}
roleRef:
  kind: ClusterRole
  name: {{ $appName }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ $appName }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $appName }}
spec:
  selector:
    matchLabels:
      app: {{ $appName }}
  template:
    metadata:
      labels:
        app: {{ $appName }}
    spec:
      serviceAccount: {{ $appName }}
      serviceAccountName: {{ $appName }}
      containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.15.3-debian-elasticsearch7-1.0
          env:
            - name:  FLUENT_ELASTICSEARCH_HOST
              value: "{{ $esName }}.{{ .Release.Namespace }}.svc.cluster.local"
            - name:  FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "http"
            - name: FLUENTD_SYSTEMD_CONF
              value: disable
          resources:
            limits:
              cpu: {{ .Values.fluentd.resources.limits.cpu }}
              memory: {{ .Values.fluentd.resources.limits.memory }}
            requests:
              cpu: {{ .Values.fluentd.resources.requests.cpu }}
              memory: {{ .Values.fluentd.resources.requests.memory }}
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: config
              mountPath: /fluentd/etc/kubernetes.conf
              subPath: kubernetes.conf
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: config
          configMap:
            name: {{ $appName }}