local: false # When deploying to a local cluster (e.g.: kind cluster), set this to true.

replicaCount: 1

image:
  repository: higress-registry.cn-hangzhou.cr.aliyuncs.com/higress/console
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

dnsPolicy: ClusterFirst
restartPolicy: Always
schedulerName: default-scheduler

service:
  type: ClusterIP
  port: 8080

ingress:
  className: "higress"
  annotations: {}
  hosts:
    - host: "console.higress.io"
      paths:
        - path: /
          pathType: Prefix
    - host: "demo.higress.io"
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: 250m
    memory: 512Mi

nodeSelector: {}
affinity: {}
tolerations: {}

admin:
  username: admin
  displayName: Admin
  password: 
    length: 8 # The length of random password generated during installation
    value: "" # If set, the value will be used as the admin password for login, and Helm won't generate a random password.

grafana:
  replicas: 1
  image:
    repository: grafana/grafana
    tag: 9.3.6
  ingress:
    path: /grafana # Only pathType of Prefix is supported
  port: 3000
  storage: 1Gi
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
prometheus:
  replicas: 1
  image:
    repository: prom/prometheus
    tag: v2.40.7
  ingress:
    path: /prometheus # Only pathType of Prefix is supported
  port: 9090
  storage: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 2Gi

elasticsearch:
  namespace: efk
  replicas: 3
  env:
    javaOpts: "-Xms512m -Xmx512m"
    maxMapCount: 262144
    ulimit: 65536
  resources:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 256Mi
  volumeClaim:
    accessMode: ReadWriteOnce
    storageClassName: standard
    storage: 3Gi
kibana:
  namespace: efk
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
fluentd:
  namespace: efk
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 200Mi
  targets:
    - namespace: higress-system
      name: higress-gateway
  es:
    host: elasticsearch.{{ .Values.elasticsearch.namespace }}
    port: 9200
  flushThreadCount: 2
  flushInterval: 5s
  retryMaxInterval: 30
